/*
The Nature Of Code - Introduction:
"Random walker using Perlin noise and colors generated by Gaussian distribution."
*/

import java.util.Random;

Random generator;

float gaussian(int mean, int sd) {
  float num = (float) generator.nextGaussian();
  float val = sd * num + mean;
  return val;
}

Walker w;

void setup() {
  size(640,340);
  background(255);
  generator = new Random();
  w = new Walker();
  //frameRate(100);
}

void draw() {
  w.step();
  w.setColors();
  w.display();
}

class Walker {
  float x,y;
  float tx,ty;
  int red, blue, green;
  
  Walker() {
    tx = 0;
    ty = 1000;
  }
  
  void step() {
    float nx = noise(tx);
    float ny = noise(ty);
    
    x = map(nx,0,1,0,width);
    y = map(ny,0,1,0,height);

    tx+=0.01;
    ty+=0.01;
     
    // Stay on the screen
    //x = constrain(x, 0, width-1);
    //y = constrain(y, 0, height-1);
  }
  
  void setColors () {
    red = (int) gaussian(125,60);
    blue = (int) gaussian(125,60);
    green = (int) gaussian(125,60);
  }
  
  
  void display () {
    strokeWeight(0.001);
    stroke(255);
    fill(red, green, blue,80);
    ellipse(x,y,5,5);
  }

}
